name: dashboard
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - sqlalchemy
  - pip
  - pip:
      - hummingbot
      - hummingbot-api-client
      - nest_asyncio
      - pydantic
      - streamlit
      - watchdog
      - python-dotenv
      - plotly==5.24.1
      - pycoingecko
      - glom
      - defillama
      - statsmodels
      - pandas_ta==0.3.14b
      - pyyaml
      - pathlib
      - streamlit-authenticator==0.3.2
      - flake8
      - isort
      - pre-commit
